version: '3.3'
services:
  quake2:
    build: .
    user: linuxgsm
    environment:
      - GAMESERVER=q2server
    ports:
      - 27910:27910/udp
    restart: unless-stopped
    network_mode: host
    volumes:
      - lgsm:/home/linuxgsm
      - ./q2server.cfg.lgsm:/home/linuxgsm/lgsm/config-lgsm/q2server/q2server.cfg
      - ./q2server.cfg.quake2:/home/linuxgsm/serverfiles/baseq2/q2server.cfg
volumes:
  lgsm:
### Remember to chown 750 any file you want to mount in there. ###
